---
title: "CS710 - Advanced Data Visualization Final"
author: "Katherine Hansen"
output:
  html_document:
    df_print: paged
---

```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(ggpubr)
library(gganimate)
library(gifski)
library(transformr)
```


```{r}
data <- read.csv("cause_of_deaths.csv")
head(data)
```


```{r}
# Selecting the years we are interested in for this project
years <- c("2001", "2002","2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017","2018")


# Adding a new column that will hold the sum of all deaths
# The dataset contains an individual count for each year, but I am interested in cumulative deaths
df <- data.frame(matrix(ncol = 3, nrow = 0))
names <- c("Country", "Year", "Sum of Deaths")
colnames(df) <- names
df

# Adding cumulative counts to their proper column
for(year in years){
    data_temp <- data[data$Year <= year & data$Year >= "2000" & (data$Country.Territory == "Afghanistan" | data$Country.Territory == "Iraq" | data$Country.Territory == "United States"), c(1, 24)]
    
      afg_sum <- sum(data_temp[data_temp$Country.Territory == "Afghanistan", c(2)])
      df[nrow(df) + 1,] <- list("Afghanistan", year, afg_sum)
      
      iraq_sum <- sum(data_temp[data_temp$Country.Territory == "Iraq", c(2)])
      df[nrow(df) + 1,] <- list("Iraq", year, iraq_sum)
      
      us_sum <- sum(data_temp[data_temp$Country.Territory == "United States", c(2)])
      df[nrow(df) + 1,] <- list("United States", year, us_sum)
      
}
df[,"Year"] = as.numeric(df[,"Year"])
df
```

```{r}
# Finding proportions of deaths in Iraq/US and Afghanistan/US

afg <- df[df$Country == "Afghanistan" & df$Year == "2018", c(3)]
iraq <- df[df$Country == "Iraq" & df$Year == "2018", c(3)]
us <- df[df$Country == "United States" & df$Year == "2018", c(3)]

print(iraq/us)
print(afg/us)
```


```{r}
# Defining my visualization
 g <- ggplot(data = df, aes(x = Year, y = `Sum of Deaths`, color = Country, group = Country)) +
  geom_point(size = 4) + 
  geom_line(linewidth = 2.5) +
  scale_color_manual(values = c('#0072b2', "#009e73", "#d55e00")) +
  theme_minimal() +
  xlab("Year") +
  ylab("Cumulative Deaths from Conflict and Terrorism") +
  ylim(0,400000) +
  labs(title = "Were Iraq and Afghanistan disproportionately affected by death in the 'War on Terror'?") + 
  scale_y_continuous(labels = scales::comma) +
  theme(axis.text.x = element_text(hjust = 1, face = "bold", size = 20),
        axis.text.y = element_text(hjust = 1, face = "bold", size = 20),
        plot.title = element_text(hjust = 0.5, size = 26),
        plot.subtitle = element_text(hjust = 0.5, size = 20),
        axis.title = element_text(size=25),
        legend.key.size = unit(3, 'cm'),
        legend.text = element_text(size=15),
        legend.title = element_text(size=18))

g

# Creating an animation
# The animation takes several minutes to render
anim <- g + geom_line() + 
  geom_point(size = 2) +
  transition_reveal(Year)

animate(anim, 600, fps = 20,  width = 1200, height = 600,
        renderer = gifski_renderer("deaths.gif"))
```

